# Generated by Django 3.0.8 on 2020-08-01 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('cover', models.ImageField(null=True, upload_to='uploads/images/categories', verbose_name='Обложка')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True, verbose_name='URL-псевдоним')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='uploads/images/items', verbose_name='Изображение')),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Средняя цена')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True, verbose_name='URL-псевдоним')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('body', models.TextField(default='', verbose_name='Текст')),
                ('cover', models.ImageField(null=True, upload_to='uploads/images/suggestions', verbose_name='Обложка')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True, verbose_name='URL-псевдоним')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ManyToManyField(to='suggestions.Category', verbose_name='Категории')),
                ('toys', models.ManyToManyField(to='suggestions.Item', verbose_name='Требуемый инвентарь')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
